//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.10.0
//     from Assets/Scripts/Pal3.Game/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Pal3.Game.Input
{
    public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""5f19a406-b3a0-4a55-903c-168d98a1703f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""bbc37652-5348-4162-aa9e-890e2c6611f5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""3e463f7c-706d-4907-9c9b-01c18f800735"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""c7524656-98fb-4308-9d3d-2363a99aaea9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnTap"",
                    ""type"": ""Button"",
                    ""id"": ""3c6d41cf-9fd5-40ea-8ec9-cfe9a50c77a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnMove"",
                    ""type"": ""PassThrough"",
                    ""id"": ""79b15688-6742-487b-96da-69b6cd3db004"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnDoubleTap"",
                    ""type"": ""Button"",
                    ""id"": ""db9d1c36-c4b2-47d9-99e0-938a7c1f4d58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCameraClockwise"",
                    ""type"": ""Button"",
                    ""id"": ""445fdece-b53a-4ccb-a564-724e21f8b993"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCameraCounterClockwise"",
                    ""type"": ""Button"",
                    ""id"": ""1a6a7e90-5774-4f8e-be6c-f14479200028"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnScroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a09c31cc-f83f-4207-8263-7e2f04d2dec1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortalTo"",
                    ""type"": ""Button"",
                    ""id"": ""152f2c30-df2e-4aff-bd17-4980232f36ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch0Start"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e1366eef-a6e7-40e4-957a-164a14ea2ebf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch0Delta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b62e6eea-8404-487e-b001-552b823dfa28"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch1Start"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4872d24a-188d-48c5-b764-739ee0962300"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch1Delta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7d51ada6-770d-4abb-bccb-7f9a60d45860"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleStorySelector"",
                    ""type"": ""Button"",
                    ""id"": ""58d6c2f0-684c-4453-9d6c-261e37881b3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleWorldMap"",
                    ""type"": ""Button"",
                    ""id"": ""c8c9d299-5a22-4938-b5c8-648116b188b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchToPreviousPlayerActor"",
                    ""type"": ""Button"",
                    ""id"": ""6270dea5-1f3b-4769-921d-cdf592367ba9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchToNextPlayerActor"",
                    ""type"": ""Button"",
                    ""id"": ""a350c9fa-4040-4a4d-b407-9e9a93ee1ec3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c38d0e0-c4b2-447f-bb72-d8d5fc3fd2e6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9831b1b-0a4e-4581-94d8-c82a3eedddce"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9ade336-36f7-4d53-aa5d-e4017f5d0a6e"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0976b58-ef09-4370-9574-a1589173742e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbd2665e-f0cf-460f-8f5b-607c3a2802cc"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard Arrow Keys"",
                    ""id"": ""e35f27c6-550f-4f93-9cb2-ed6e7bbdea02"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c4b1574f-4f7d-46e1-afed-d5d4e0caf288"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a6ac77fe-34fe-462f-a68e-09e148f375cf"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4b0482fb-7e74-4a41-a5c0-8c31fb103313"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""31d85ed1-4def-46b8-b120-8c5dce5890bd"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0968cb64-8274-4260-9c62-9cba759ca4ab"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eba8dc6-2c21-41f6-8318-572955eeb71a"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6b54252-95bc-4d11-b567-5cc2c3ca5002"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0c40cd3-acc9-48a1-845c-0319a98eb4a2"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""326b85ea-e447-4322-8c68-2c2f7362d46d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnDoubleTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daa3277a-7257-452a-acd2-c8ea8ee34080"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCameraClockwise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""795b72b8-65f9-49bb-a352-a15e10c7b261"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""RotateCameraClockwise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4626cea-9349-487c-b348-10e4ee4a60be"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCameraCounterClockwise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c8591f6-45f7-4061-9ce9-3cf253dece26"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""RotateCameraCounterClockwise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25543604-ffe6-4765-9e09-1aa3679a446a"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9983312b-6d86-42eb-beac-698c9041ddfd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortalTo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c67bc5dd-aae4-4272-b0ad-41b9ea3a0bfd"",
                    ""path"": ""<Touchscreen>/touch0/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1774904c-7f70-4079-96dd-d2c66aaec6b4"",
                    ""path"": ""<Touchscreen>/touch1/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54a95e5f-f024-43f4-a265-d3e4121fe8c5"",
                    ""path"": ""<Touchscreen>/touch1/startPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dac9f7d-d839-4191-8297-412ee2c83b34"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStorySelector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80e3a477-108f-4c5b-ae22-3cd71a64e87b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStorySelector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4460ae52-4a0c-496b-9d61-4675024a3498"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStorySelector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""954e0003-1b73-4c17-a01a-4dccbafa8ca9"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleWorldMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a6a4aa8-66b8-46f3-a86d-e768d3c6a249"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleWorldMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c4ae24e-2744-4423-bd5b-eec9eb539fb0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchToPreviousPlayerActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cd48e88-fdd1-49c2-9be2-0157b27fac6e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchToNextPlayerActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0aec67f-4bb7-4d1b-b205-30dd16894caf"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchToNextPlayerActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eee33256-f6ae-4bd6-8777-a5c521602aa4"",
                    ""path"": ""<Touchscreen>/touch0/startPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Cutscene"",
            ""id"": ""ee8b7282-e84e-4c06-9680-05fb5bdddceb"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""c29942dd-5019-490c-a7d9-09236b1b858f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a20ff6d7-d18b-42b4-9935-29fb16f77e73"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7460c377-5507-47a6-b0a8-6696a0d654bd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2a6d6f7-8ab2-4921-a7c4-2ae0da090b8e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c17122c6-462b-49ea-8c1e-e15f43b95f48"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""VideoPlaying"",
            ""id"": ""ebda0501-6118-4277-9617-64f8f08ba12b"",
            ""actions"": [
                {
                    ""name"": ""SkipVideo"",
                    ""type"": ""Button"",
                    ""id"": ""7ee4f03c-ec5c-4e58-9d90-ee2219985da6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4ac13274-67b2-4f13-a8d3-f9cbf1fc78dd"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipVideo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b35a5aa3-ac29-4a26-a77b-080723989302"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipVideo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ea955e9-ed45-4e99-a2e5-d663e5807fdb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipVideo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""ba041dd0-cb9d-4991-bd85-d4542c2b1300"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5c559bc6-fbe2-4a8b-ad85-f086001768ca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""c3bfd39c-ca2e-4094-b82e-2d8c29da0ed8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""6967225e-b6c4-423c-86f8-35e509aca591"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""efefafd1-4f82-47bf-a636-49d3d351c03c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""48515450-8686-4060-abb5-2ee9debca659"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f1510aeb-6482-42c7-b479-f4119d75e387"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ba4bef8b-c798-4923-949c-56aa5aab214f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3a870725-d060-40ed-8f7d-91ff21e2e4dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2810cb27-4d18-44a0-9c96-4499e3e71637"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7161fa71-8e92-482f-b86c-98287c1b2e75"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleWorldMap"",
                    ""type"": ""Button"",
                    ""id"": ""c0eb7e88-5de5-45e8-b93a-d5a669cb1e87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleStorySelector"",
                    ""type"": ""Button"",
                    ""id"": ""ac2e00e5-0cba-4594-96e0-b8a39e97c5f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitCurrentShowingMenu"",
                    ""type"": ""Button"",
                    ""id"": ""37efe51b-ffd5-4283-b253-65611750e358"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""65c4e90d-2ac5-44b3-a39e-814daa6db6d2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6fe4dd78-93ef-4dba-9127-b6da66cbdd78"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e2676917-c6fb-4e4c-9b9c-e72210c8a9d1"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""31db7c6c-a5a2-4943-9d71-ec8926387878"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5069972b-befc-49c7-ad28-70d86dfb8e71"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""88ddcb70-1577-4ef0-b6c7-dbedd5d2eb1f"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6a9072ac-de88-4adf-99b2-1b902af5d2bb"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f4b061ca-aa23-41e7-a542-d04c1077c125"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bc2d7cf9-c6ac-44ca-b74e-500043bec553"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""18cb396d-7a2a-41e2-ac43-9cdf4362b8ad"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""bb932771-dc04-481c-9f5f-90870ec77e73"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c5817355-4b66-4510-a03a-cc2343005870"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0bd4c292-652d-4fdd-a4e7-32b48e96c4e0"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4efabf16-59a2-41a7-838d-4fc60d96f8db"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7403a240-5232-463f-ae39-8fc64aee0c83"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""dc8e8582-dbb9-40ac-89ec-f97e3e4337de"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""862c2a10-c3f2-4c56-a13b-6a0601656063"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a8cdcd06-480f-492e-82a0-e97dcaa08a2c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8f4f117f-e0ef-448e-b73c-6b2d7f673b50"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df46b9c1-db36-4e8f-9226-1b700807ac7a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2c98fe1b-6e24-4e12-b1ba-b5e8adcf79cd"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fb054a9-663b-465d-a3c6-54b37e2b116b"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72ce28f0-65fc-47a1-9707-44e0e7176991"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""471a789c-380c-4079-8eda-4261ef52d6ce"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0ff19d3-86ea-4439-b3db-614b7b32699c"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d839276a-db0d-4cc1-a7c8-101e536f470c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84c65078-8e48-4cd0-8933-c8e84981a5c5"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdded065-704e-4ee7-94c2-78142d89ba33"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""292d53f7-c5fd-49d9-9d80-c8a6514c3442"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1a21f8e-c8bb-45ca-8e19-4c0996b7977b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b0d3673-e976-4484-b4a0-b5288d94b866"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e568441a-ba21-4a27-96ea-f67708a0370a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6620c37-b48c-48e7-b9ca-af312a070198"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c21b2f6-d602-4c79-ac54-3675b2f2e85d"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d9749bf-4ff4-4c1c-b3b8-8fd519c213aa"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleWorldMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2fa38b5-fad5-4477-a7f1-815554cea62d"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleWorldMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e85d718-ef17-47b9-a6a8-9d4a19174180"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStorySelector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c73bf36-9883-4a4a-b981-18615f0a9230"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStorySelector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6956fcc8-e046-47f7-a9f3-6b9ca0030f2e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStorySelector"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""637d83eb-8f9f-4077-b91c-4b1ca0f7890b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitCurrentShowingMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6817bb0f-608a-42c7-a862-8c96c956dd15"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitCurrentShowingMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""76cd9d4b-6f9c-4f58-a69b-859c0b6d3c6b"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Combat"",
            ""id"": ""49ab487c-79cc-4f76-9e0f-872d16db5f30"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
            m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
            m_Gameplay_Menu = m_Gameplay.FindAction("Menu", throwIfNotFound: true);
            m_Gameplay_OnTap = m_Gameplay.FindAction("OnTap", throwIfNotFound: true);
            m_Gameplay_OnMove = m_Gameplay.FindAction("OnMove", throwIfNotFound: true);
            m_Gameplay_OnDoubleTap = m_Gameplay.FindAction("OnDoubleTap", throwIfNotFound: true);
            m_Gameplay_RotateCameraClockwise = m_Gameplay.FindAction("RotateCameraClockwise", throwIfNotFound: true);
            m_Gameplay_RotateCameraCounterClockwise = m_Gameplay.FindAction("RotateCameraCounterClockwise", throwIfNotFound: true);
            m_Gameplay_OnScroll = m_Gameplay.FindAction("OnScroll", throwIfNotFound: true);
            m_Gameplay_PortalTo = m_Gameplay.FindAction("PortalTo", throwIfNotFound: true);
            m_Gameplay_Touch0Start = m_Gameplay.FindAction("Touch0Start", throwIfNotFound: true);
            m_Gameplay_Touch0Delta = m_Gameplay.FindAction("Touch0Delta", throwIfNotFound: true);
            m_Gameplay_Touch1Start = m_Gameplay.FindAction("Touch1Start", throwIfNotFound: true);
            m_Gameplay_Touch1Delta = m_Gameplay.FindAction("Touch1Delta", throwIfNotFound: true);
            m_Gameplay_ToggleStorySelector = m_Gameplay.FindAction("ToggleStorySelector", throwIfNotFound: true);
            m_Gameplay_ToggleWorldMap = m_Gameplay.FindAction("ToggleWorldMap", throwIfNotFound: true);
            m_Gameplay_SwitchToPreviousPlayerActor = m_Gameplay.FindAction("SwitchToPreviousPlayerActor", throwIfNotFound: true);
            m_Gameplay_SwitchToNextPlayerActor = m_Gameplay.FindAction("SwitchToNextPlayerActor", throwIfNotFound: true);
            // Cutscene
            m_Cutscene = asset.FindActionMap("Cutscene", throwIfNotFound: true);
            m_Cutscene_Continue = m_Cutscene.FindAction("Continue", throwIfNotFound: true);
            // VideoPlaying
            m_VideoPlaying = asset.FindActionMap("VideoPlaying", throwIfNotFound: true);
            m_VideoPlaying_SkipVideo = m_VideoPlaying.FindAction("SkipVideo", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
            m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
            m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
            m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
            m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
            m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
            m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
            m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
            m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
            m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
            m_UI_ToggleWorldMap = m_UI.FindAction("ToggleWorldMap", throwIfNotFound: true);
            m_UI_ToggleStorySelector = m_UI.FindAction("ToggleStorySelector", throwIfNotFound: true);
            m_UI_ExitCurrentShowingMenu = m_UI.FindAction("ExitCurrentShowingMenu", throwIfNotFound: true);
            // Debug
            m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
            // Combat
            m_Combat = asset.FindActionMap("Combat", throwIfNotFound: true);
        }

        ~@PlayerInputActions()
        {
            UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, PlayerInputActions.Gameplay.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Cutscene.enabled, "This will cause a leak and performance issues, PlayerInputActions.Cutscene.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_VideoPlaying.enabled, "This will cause a leak and performance issues, PlayerInputActions.VideoPlaying.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, PlayerInputActions.UI.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Debug.enabled, "This will cause a leak and performance issues, PlayerInputActions.Debug.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Combat.enabled, "This will cause a leak and performance issues, PlayerInputActions.Combat.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
        private readonly InputAction m_Gameplay_Movement;
        private readonly InputAction m_Gameplay_Interact;
        private readonly InputAction m_Gameplay_Menu;
        private readonly InputAction m_Gameplay_OnTap;
        private readonly InputAction m_Gameplay_OnMove;
        private readonly InputAction m_Gameplay_OnDoubleTap;
        private readonly InputAction m_Gameplay_RotateCameraClockwise;
        private readonly InputAction m_Gameplay_RotateCameraCounterClockwise;
        private readonly InputAction m_Gameplay_OnScroll;
        private readonly InputAction m_Gameplay_PortalTo;
        private readonly InputAction m_Gameplay_Touch0Start;
        private readonly InputAction m_Gameplay_Touch0Delta;
        private readonly InputAction m_Gameplay_Touch1Start;
        private readonly InputAction m_Gameplay_Touch1Delta;
        private readonly InputAction m_Gameplay_ToggleStorySelector;
        private readonly InputAction m_Gameplay_ToggleWorldMap;
        private readonly InputAction m_Gameplay_SwitchToPreviousPlayerActor;
        private readonly InputAction m_Gameplay_SwitchToNextPlayerActor;
        public struct GameplayActions
        {
            private @PlayerInputActions m_Wrapper;
            public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
            public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
            public InputAction @Menu => m_Wrapper.m_Gameplay_Menu;
            public InputAction @OnTap => m_Wrapper.m_Gameplay_OnTap;
            public InputAction @OnMove => m_Wrapper.m_Gameplay_OnMove;
            public InputAction @OnDoubleTap => m_Wrapper.m_Gameplay_OnDoubleTap;
            public InputAction @RotateCameraClockwise => m_Wrapper.m_Gameplay_RotateCameraClockwise;
            public InputAction @RotateCameraCounterClockwise => m_Wrapper.m_Gameplay_RotateCameraCounterClockwise;
            public InputAction @OnScroll => m_Wrapper.m_Gameplay_OnScroll;
            public InputAction @PortalTo => m_Wrapper.m_Gameplay_PortalTo;
            public InputAction @Touch0Start => m_Wrapper.m_Gameplay_Touch0Start;
            public InputAction @Touch0Delta => m_Wrapper.m_Gameplay_Touch0Delta;
            public InputAction @Touch1Start => m_Wrapper.m_Gameplay_Touch1Start;
            public InputAction @Touch1Delta => m_Wrapper.m_Gameplay_Touch1Delta;
            public InputAction @ToggleStorySelector => m_Wrapper.m_Gameplay_ToggleStorySelector;
            public InputAction @ToggleWorldMap => m_Wrapper.m_Gameplay_ToggleWorldMap;
            public InputAction @SwitchToPreviousPlayerActor => m_Wrapper.m_Gameplay_SwitchToPreviousPlayerActor;
            public InputAction @SwitchToNextPlayerActor => m_Wrapper.m_Gameplay_SwitchToNextPlayerActor;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void AddCallbacks(IGameplayActions instance)
            {
                if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @OnTap.started += instance.OnOnTap;
                @OnTap.performed += instance.OnOnTap;
                @OnTap.canceled += instance.OnOnTap;
                @OnMove.started += instance.OnOnMove;
                @OnMove.performed += instance.OnOnMove;
                @OnMove.canceled += instance.OnOnMove;
                @OnDoubleTap.started += instance.OnOnDoubleTap;
                @OnDoubleTap.performed += instance.OnOnDoubleTap;
                @OnDoubleTap.canceled += instance.OnOnDoubleTap;
                @RotateCameraClockwise.started += instance.OnRotateCameraClockwise;
                @RotateCameraClockwise.performed += instance.OnRotateCameraClockwise;
                @RotateCameraClockwise.canceled += instance.OnRotateCameraClockwise;
                @RotateCameraCounterClockwise.started += instance.OnRotateCameraCounterClockwise;
                @RotateCameraCounterClockwise.performed += instance.OnRotateCameraCounterClockwise;
                @RotateCameraCounterClockwise.canceled += instance.OnRotateCameraCounterClockwise;
                @OnScroll.started += instance.OnOnScroll;
                @OnScroll.performed += instance.OnOnScroll;
                @OnScroll.canceled += instance.OnOnScroll;
                @PortalTo.started += instance.OnPortalTo;
                @PortalTo.performed += instance.OnPortalTo;
                @PortalTo.canceled += instance.OnPortalTo;
                @Touch0Start.started += instance.OnTouch0Start;
                @Touch0Start.performed += instance.OnTouch0Start;
                @Touch0Start.canceled += instance.OnTouch0Start;
                @Touch0Delta.started += instance.OnTouch0Delta;
                @Touch0Delta.performed += instance.OnTouch0Delta;
                @Touch0Delta.canceled += instance.OnTouch0Delta;
                @Touch1Start.started += instance.OnTouch1Start;
                @Touch1Start.performed += instance.OnTouch1Start;
                @Touch1Start.canceled += instance.OnTouch1Start;
                @Touch1Delta.started += instance.OnTouch1Delta;
                @Touch1Delta.performed += instance.OnTouch1Delta;
                @Touch1Delta.canceled += instance.OnTouch1Delta;
                @ToggleStorySelector.started += instance.OnToggleStorySelector;
                @ToggleStorySelector.performed += instance.OnToggleStorySelector;
                @ToggleStorySelector.canceled += instance.OnToggleStorySelector;
                @ToggleWorldMap.started += instance.OnToggleWorldMap;
                @ToggleWorldMap.performed += instance.OnToggleWorldMap;
                @ToggleWorldMap.canceled += instance.OnToggleWorldMap;
                @SwitchToPreviousPlayerActor.started += instance.OnSwitchToPreviousPlayerActor;
                @SwitchToPreviousPlayerActor.performed += instance.OnSwitchToPreviousPlayerActor;
                @SwitchToPreviousPlayerActor.canceled += instance.OnSwitchToPreviousPlayerActor;
                @SwitchToNextPlayerActor.started += instance.OnSwitchToNextPlayerActor;
                @SwitchToNextPlayerActor.performed += instance.OnSwitchToNextPlayerActor;
                @SwitchToNextPlayerActor.canceled += instance.OnSwitchToNextPlayerActor;
            }

            private void UnregisterCallbacks(IGameplayActions instance)
            {
                @Movement.started -= instance.OnMovement;
                @Movement.performed -= instance.OnMovement;
                @Movement.canceled -= instance.OnMovement;
                @Interact.started -= instance.OnInteract;
                @Interact.performed -= instance.OnInteract;
                @Interact.canceled -= instance.OnInteract;
                @Menu.started -= instance.OnMenu;
                @Menu.performed -= instance.OnMenu;
                @Menu.canceled -= instance.OnMenu;
                @OnTap.started -= instance.OnOnTap;
                @OnTap.performed -= instance.OnOnTap;
                @OnTap.canceled -= instance.OnOnTap;
                @OnMove.started -= instance.OnOnMove;
                @OnMove.performed -= instance.OnOnMove;
                @OnMove.canceled -= instance.OnOnMove;
                @OnDoubleTap.started -= instance.OnOnDoubleTap;
                @OnDoubleTap.performed -= instance.OnOnDoubleTap;
                @OnDoubleTap.canceled -= instance.OnOnDoubleTap;
                @RotateCameraClockwise.started -= instance.OnRotateCameraClockwise;
                @RotateCameraClockwise.performed -= instance.OnRotateCameraClockwise;
                @RotateCameraClockwise.canceled -= instance.OnRotateCameraClockwise;
                @RotateCameraCounterClockwise.started -= instance.OnRotateCameraCounterClockwise;
                @RotateCameraCounterClockwise.performed -= instance.OnRotateCameraCounterClockwise;
                @RotateCameraCounterClockwise.canceled -= instance.OnRotateCameraCounterClockwise;
                @OnScroll.started -= instance.OnOnScroll;
                @OnScroll.performed -= instance.OnOnScroll;
                @OnScroll.canceled -= instance.OnOnScroll;
                @PortalTo.started -= instance.OnPortalTo;
                @PortalTo.performed -= instance.OnPortalTo;
                @PortalTo.canceled -= instance.OnPortalTo;
                @Touch0Start.started -= instance.OnTouch0Start;
                @Touch0Start.performed -= instance.OnTouch0Start;
                @Touch0Start.canceled -= instance.OnTouch0Start;
                @Touch0Delta.started -= instance.OnTouch0Delta;
                @Touch0Delta.performed -= instance.OnTouch0Delta;
                @Touch0Delta.canceled -= instance.OnTouch0Delta;
                @Touch1Start.started -= instance.OnTouch1Start;
                @Touch1Start.performed -= instance.OnTouch1Start;
                @Touch1Start.canceled -= instance.OnTouch1Start;
                @Touch1Delta.started -= instance.OnTouch1Delta;
                @Touch1Delta.performed -= instance.OnTouch1Delta;
                @Touch1Delta.canceled -= instance.OnTouch1Delta;
                @ToggleStorySelector.started -= instance.OnToggleStorySelector;
                @ToggleStorySelector.performed -= instance.OnToggleStorySelector;
                @ToggleStorySelector.canceled -= instance.OnToggleStorySelector;
                @ToggleWorldMap.started -= instance.OnToggleWorldMap;
                @ToggleWorldMap.performed -= instance.OnToggleWorldMap;
                @ToggleWorldMap.canceled -= instance.OnToggleWorldMap;
                @SwitchToPreviousPlayerActor.started -= instance.OnSwitchToPreviousPlayerActor;
                @SwitchToPreviousPlayerActor.performed -= instance.OnSwitchToPreviousPlayerActor;
                @SwitchToPreviousPlayerActor.canceled -= instance.OnSwitchToPreviousPlayerActor;
                @SwitchToNextPlayerActor.started -= instance.OnSwitchToNextPlayerActor;
                @SwitchToNextPlayerActor.performed -= instance.OnSwitchToNextPlayerActor;
                @SwitchToNextPlayerActor.canceled -= instance.OnSwitchToNextPlayerActor;
            }

            public void RemoveCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGameplayActions instance)
            {
                foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);

        // Cutscene
        private readonly InputActionMap m_Cutscene;
        private List<ICutsceneActions> m_CutsceneActionsCallbackInterfaces = new List<ICutsceneActions>();
        private readonly InputAction m_Cutscene_Continue;
        public struct CutsceneActions
        {
            private @PlayerInputActions m_Wrapper;
            public CutsceneActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Continue => m_Wrapper.m_Cutscene_Continue;
            public InputActionMap Get() { return m_Wrapper.m_Cutscene; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CutsceneActions set) { return set.Get(); }
            public void AddCallbacks(ICutsceneActions instance)
            {
                if (instance == null || m_Wrapper.m_CutsceneActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CutsceneActionsCallbackInterfaces.Add(instance);
                @Continue.started += instance.OnContinue;
                @Continue.performed += instance.OnContinue;
                @Continue.canceled += instance.OnContinue;
            }

            private void UnregisterCallbacks(ICutsceneActions instance)
            {
                @Continue.started -= instance.OnContinue;
                @Continue.performed -= instance.OnContinue;
                @Continue.canceled -= instance.OnContinue;
            }

            public void RemoveCallbacks(ICutsceneActions instance)
            {
                if (m_Wrapper.m_CutsceneActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICutsceneActions instance)
            {
                foreach (var item in m_Wrapper.m_CutsceneActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CutsceneActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CutsceneActions @Cutscene => new CutsceneActions(this);

        // VideoPlaying
        private readonly InputActionMap m_VideoPlaying;
        private List<IVideoPlayingActions> m_VideoPlayingActionsCallbackInterfaces = new List<IVideoPlayingActions>();
        private readonly InputAction m_VideoPlaying_SkipVideo;
        public struct VideoPlayingActions
        {
            private @PlayerInputActions m_Wrapper;
            public VideoPlayingActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @SkipVideo => m_Wrapper.m_VideoPlaying_SkipVideo;
            public InputActionMap Get() { return m_Wrapper.m_VideoPlaying; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(VideoPlayingActions set) { return set.Get(); }
            public void AddCallbacks(IVideoPlayingActions instance)
            {
                if (instance == null || m_Wrapper.m_VideoPlayingActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_VideoPlayingActionsCallbackInterfaces.Add(instance);
                @SkipVideo.started += instance.OnSkipVideo;
                @SkipVideo.performed += instance.OnSkipVideo;
                @SkipVideo.canceled += instance.OnSkipVideo;
            }

            private void UnregisterCallbacks(IVideoPlayingActions instance)
            {
                @SkipVideo.started -= instance.OnSkipVideo;
                @SkipVideo.performed -= instance.OnSkipVideo;
                @SkipVideo.canceled -= instance.OnSkipVideo;
            }

            public void RemoveCallbacks(IVideoPlayingActions instance)
            {
                if (m_Wrapper.m_VideoPlayingActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IVideoPlayingActions instance)
            {
                foreach (var item in m_Wrapper.m_VideoPlayingActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_VideoPlayingActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public VideoPlayingActions @VideoPlaying => new VideoPlayingActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
        private readonly InputAction m_UI_Navigate;
        private readonly InputAction m_UI_Submit;
        private readonly InputAction m_UI_Cancel;
        private readonly InputAction m_UI_Point;
        private readonly InputAction m_UI_Click;
        private readonly InputAction m_UI_ScrollWheel;
        private readonly InputAction m_UI_MiddleClick;
        private readonly InputAction m_UI_RightClick;
        private readonly InputAction m_UI_TrackedDevicePosition;
        private readonly InputAction m_UI_TrackedDeviceOrientation;
        private readonly InputAction m_UI_ToggleWorldMap;
        private readonly InputAction m_UI_ToggleStorySelector;
        private readonly InputAction m_UI_ExitCurrentShowingMenu;
        public struct UIActions
        {
            private @PlayerInputActions m_Wrapper;
            public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
            public InputAction @Submit => m_Wrapper.m_UI_Submit;
            public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
            public InputAction @Point => m_Wrapper.m_UI_Point;
            public InputAction @Click => m_Wrapper.m_UI_Click;
            public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
            public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
            public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
            public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
            public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
            public InputAction @ToggleWorldMap => m_Wrapper.m_UI_ToggleWorldMap;
            public InputAction @ToggleStorySelector => m_Wrapper.m_UI_ToggleStorySelector;
            public InputAction @ExitCurrentShowingMenu => m_Wrapper.m_UI_ExitCurrentShowingMenu;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void AddCallbacks(IUIActions instance)
            {
                if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
                @ToggleWorldMap.started += instance.OnToggleWorldMap;
                @ToggleWorldMap.performed += instance.OnToggleWorldMap;
                @ToggleWorldMap.canceled += instance.OnToggleWorldMap;
                @ToggleStorySelector.started += instance.OnToggleStorySelector;
                @ToggleStorySelector.performed += instance.OnToggleStorySelector;
                @ToggleStorySelector.canceled += instance.OnToggleStorySelector;
                @ExitCurrentShowingMenu.started += instance.OnExitCurrentShowingMenu;
                @ExitCurrentShowingMenu.performed += instance.OnExitCurrentShowingMenu;
                @ExitCurrentShowingMenu.canceled += instance.OnExitCurrentShowingMenu;
            }

            private void UnregisterCallbacks(IUIActions instance)
            {
                @Navigate.started -= instance.OnNavigate;
                @Navigate.performed -= instance.OnNavigate;
                @Navigate.canceled -= instance.OnNavigate;
                @Submit.started -= instance.OnSubmit;
                @Submit.performed -= instance.OnSubmit;
                @Submit.canceled -= instance.OnSubmit;
                @Cancel.started -= instance.OnCancel;
                @Cancel.performed -= instance.OnCancel;
                @Cancel.canceled -= instance.OnCancel;
                @Point.started -= instance.OnPoint;
                @Point.performed -= instance.OnPoint;
                @Point.canceled -= instance.OnPoint;
                @Click.started -= instance.OnClick;
                @Click.performed -= instance.OnClick;
                @Click.canceled -= instance.OnClick;
                @ScrollWheel.started -= instance.OnScrollWheel;
                @ScrollWheel.performed -= instance.OnScrollWheel;
                @ScrollWheel.canceled -= instance.OnScrollWheel;
                @MiddleClick.started -= instance.OnMiddleClick;
                @MiddleClick.performed -= instance.OnMiddleClick;
                @MiddleClick.canceled -= instance.OnMiddleClick;
                @RightClick.started -= instance.OnRightClick;
                @RightClick.performed -= instance.OnRightClick;
                @RightClick.canceled -= instance.OnRightClick;
                @TrackedDevicePosition.started -= instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed -= instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled -= instance.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started -= instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed -= instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled -= instance.OnTrackedDeviceOrientation;
                @ToggleWorldMap.started -= instance.OnToggleWorldMap;
                @ToggleWorldMap.performed -= instance.OnToggleWorldMap;
                @ToggleWorldMap.canceled -= instance.OnToggleWorldMap;
                @ToggleStorySelector.started -= instance.OnToggleStorySelector;
                @ToggleStorySelector.performed -= instance.OnToggleStorySelector;
                @ToggleStorySelector.canceled -= instance.OnToggleStorySelector;
                @ExitCurrentShowingMenu.started -= instance.OnExitCurrentShowingMenu;
                @ExitCurrentShowingMenu.performed -= instance.OnExitCurrentShowingMenu;
                @ExitCurrentShowingMenu.canceled -= instance.OnExitCurrentShowingMenu;
            }

            public void RemoveCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIActions instance)
            {
                foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIActions @UI => new UIActions(this);

        // Debug
        private readonly InputActionMap m_Debug;
        private List<IDebugActions> m_DebugActionsCallbackInterfaces = new List<IDebugActions>();
        public struct DebugActions
        {
            private @PlayerInputActions m_Wrapper;
            public DebugActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_Debug; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
            public void AddCallbacks(IDebugActions instance)
            {
                if (instance == null || m_Wrapper.m_DebugActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DebugActionsCallbackInterfaces.Add(instance);
            }

            private void UnregisterCallbacks(IDebugActions instance)
            {
            }

            public void RemoveCallbacks(IDebugActions instance)
            {
                if (m_Wrapper.m_DebugActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IDebugActions instance)
            {
                foreach (var item in m_Wrapper.m_DebugActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DebugActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public DebugActions @Debug => new DebugActions(this);

        // Combat
        private readonly InputActionMap m_Combat;
        private List<ICombatActions> m_CombatActionsCallbackInterfaces = new List<ICombatActions>();
        public struct CombatActions
        {
            private @PlayerInputActions m_Wrapper;
            public CombatActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_Combat; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CombatActions set) { return set.Get(); }
            public void AddCallbacks(ICombatActions instance)
            {
                if (instance == null || m_Wrapper.m_CombatActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CombatActionsCallbackInterfaces.Add(instance);
            }

            private void UnregisterCallbacks(ICombatActions instance)
            {
            }

            public void RemoveCallbacks(ICombatActions instance)
            {
                if (m_Wrapper.m_CombatActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICombatActions instance)
            {
                foreach (var item in m_Wrapper.m_CombatActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CombatActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CombatActions @Combat => new CombatActions(this);
        public interface IGameplayActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnMenu(InputAction.CallbackContext context);
            void OnOnTap(InputAction.CallbackContext context);
            void OnOnMove(InputAction.CallbackContext context);
            void OnOnDoubleTap(InputAction.CallbackContext context);
            void OnRotateCameraClockwise(InputAction.CallbackContext context);
            void OnRotateCameraCounterClockwise(InputAction.CallbackContext context);
            void OnOnScroll(InputAction.CallbackContext context);
            void OnPortalTo(InputAction.CallbackContext context);
            void OnTouch0Start(InputAction.CallbackContext context);
            void OnTouch0Delta(InputAction.CallbackContext context);
            void OnTouch1Start(InputAction.CallbackContext context);
            void OnTouch1Delta(InputAction.CallbackContext context);
            void OnToggleStorySelector(InputAction.CallbackContext context);
            void OnToggleWorldMap(InputAction.CallbackContext context);
            void OnSwitchToPreviousPlayerActor(InputAction.CallbackContext context);
            void OnSwitchToNextPlayerActor(InputAction.CallbackContext context);
        }
        public interface ICutsceneActions
        {
            void OnContinue(InputAction.CallbackContext context);
        }
        public interface IVideoPlayingActions
        {
            void OnSkipVideo(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnScrollWheel(InputAction.CallbackContext context);
            void OnMiddleClick(InputAction.CallbackContext context);
            void OnRightClick(InputAction.CallbackContext context);
            void OnTrackedDevicePosition(InputAction.CallbackContext context);
            void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
            void OnToggleWorldMap(InputAction.CallbackContext context);
            void OnToggleStorySelector(InputAction.CallbackContext context);
            void OnExitCurrentShowingMenu(InputAction.CallbackContext context);
        }
        public interface IDebugActions
        {
        }
        public interface ICombatActions
        {
        }
    }
}
