#if PAL3A

// ---------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by ConsoleCommandsAutoGen`1
// </auto-generated>
// ---------------------------------------------------------------------------------------------

namespace Pal3.Game.Command
{
    using Core.Command;
    using Core.Command.SceCommands;
    using Extensions;
    using IngameDebugConsole;

    // <auto-generated/>
    public static class ConsoleCommands
    {
        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetFacing", "Execute ActorSetFacingCommand.")]
        public static void ActorSetFacing(System.Int32 actorId, System.Int32 degrees)
        {
            Pal3.Instance.Execute(new ActorSetFacingCommand(actorId, degrees));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetWorldPosition", "Execute ActorSetWorldPositionCommand.")]
        public static void ActorSetWorldPosition(System.Int32 actorId, System.Single xPosition, System.Single zPosition)
        {
            Pal3.Instance.Execute(new ActorSetWorldPositionCommand(actorId, xPosition, zPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraSetInitialStateOnNextSceneLoad", "Execute CameraSetInitialStateOnNextSceneLoadCommand.")]
        public static void CameraSetInitialStateOnNextSceneLoad(System.Single xEulerAngle, System.Single yEulerAngle, System.Single zEulerAngle, System.Int32 initTransformOption)
        {
            Pal3.Instance.Execute(new CameraSetInitialStateOnNextSceneLoadCommand(xEulerAngle, yEulerAngle, zEulerAngle, initTransformOption));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayerActorLookAtSceneObject", "Execute PlayerActorLookAtSceneObjectCommand.")]
        public static void PlayerActorLookAtSceneObject(System.Int32 sceneObjectId)
        {
            Pal3.Instance.Execute(new PlayerActorLookAtSceneObjectCommand(sceneObjectId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayerInteractionRequest", "Execute PlayerInteractionRequest.")]
        public static void PlayerInteractionRequest()
        {
            Pal3.Instance.Execute(new PlayerInteractionRequest());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ResetGameState", "Execute ResetGameStateCommand.")]
        public static void ResetGameState()
        {
            Pal3.Instance.Execute(new ResetGameStateCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneSaveGlobalObjectActivationState", "Execute SceneSaveGlobalObjectActivationStateCommand.")]
        public static void SceneSaveGlobalObjectActivationState(System.String cityName, System.String sceneName, System.Int32 objectId, System.Boolean isActivated)
        {
            Pal3.Instance.Execute(new SceneSaveGlobalObjectActivationStateCommand(cityName, sceneName, objectId, isActivated));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneSaveGlobalObjectLayerIndex", "Execute SceneSaveGlobalObjectLayerIndexCommand.")]
        public static void SceneSaveGlobalObjectLayerIndex(System.String cityName, System.String sceneName, System.Int32 objectId, System.Byte layerIndex)
        {
            Pal3.Instance.Execute(new SceneSaveGlobalObjectLayerIndexCommand(cityName, sceneName, objectId, layerIndex));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneSaveGlobalObjectPosition", "Execute SceneSaveGlobalObjectPositionCommand.")]
        public static void SceneSaveGlobalObjectPosition(System.String cityName, System.String sceneName, System.Int32 objectId, System.Single gameBoxXPosition, System.Single gameBoxYPosition, System.Single gameBoxZPosition)
        {
            Pal3.Instance.Execute(new SceneSaveGlobalObjectPositionCommand(cityName, sceneName, objectId, gameBoxXPosition, gameBoxYPosition, gameBoxZPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneSaveGlobalObjectSwitchState", "Execute SceneSaveGlobalObjectSwitchStateCommand.")]
        public static void SceneSaveGlobalObjectSwitchState(System.String cityName, System.String sceneName, System.Int32 objectId, System.Byte switchState)
        {
            Pal3.Instance.Execute(new SceneSaveGlobalObjectSwitchStateCommand(cityName, sceneName, objectId, switchState));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneSaveGlobalObjectTimesCount", "Execute SceneSaveGlobalObjectTimesCountCommand.")]
        public static void SceneSaveGlobalObjectTimesCount(System.String cityName, System.String sceneName, System.Int32 objectId, System.Byte timesCount)
        {
            Pal3.Instance.Execute(new SceneSaveGlobalObjectTimesCountCommand(cityName, sceneName, objectId, timesCount));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneSaveGlobalObjectYRotation", "Execute SceneSaveGlobalObjectYRotationCommand.")]
        public static void SceneSaveGlobalObjectYRotation(System.String cityName, System.String sceneName, System.Int32 objectId, System.Single gameBoxYRotation)
        {
            Pal3.Instance.Execute(new SceneSaveGlobalObjectYRotationCommand(cityName, sceneName, objectId, gameBoxYRotation));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneSaveGlobalThreePhaseSwitchState", "Execute SceneSaveGlobalThreePhaseSwitchStateCommand.")]
        public static void SceneSaveGlobalThreePhaseSwitchState(System.String cityName, System.String sceneName, System.Int32 objectId, System.Int32 previousState, System.Int32 currentState)
        {
            Pal3.Instance.Execute(new SceneSaveGlobalThreePhaseSwitchStateCommand(cityName, sceneName, objectId, previousState, currentState));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SwitchPlayerActorRequest", "Execute SwitchPlayerActorRequest.")]
        public static void SwitchPlayerActorRequest()
        {
            Pal3.Instance.Execute(new SwitchPlayerActorRequest());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ToggleMainMenuRequest", "Execute ToggleMainMenuRequest.")]
        public static void ToggleMainMenuRequest()
        {
            Pal3.Instance.Execute(new ToggleMainMenuRequest());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ToggleWorldMapRequest", "Execute ToggleWorldMapRequest.")]
        public static void ToggleWorldMapRequest()
        {
            Pal3.Instance.Execute(new ToggleWorldMapRequest());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorActivate", "设置角色是否激活，参数：角色ID，是否激活（1是0否）")]
        public static void ActorActivate(System.Int32 actorId, System.Int32 isActive)
        {
            Pal3.Instance.Execute(new ActorActivateCommand(actorId, isActive));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorAddSkill", "某个主角学会新特技，参数：主角ID，特技ID")]
        public static void ActorAddSkill(System.Int32 actorId, System.Int32 skillId)
        {
            Pal3.Instance.Execute(new ActorAddSkillCommand(actorId, skillId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorAutoStand", "指定角色是否在PerformAction指令完成后自动切换成站立的动作，参数：角色ID，是否自动站立（1是0否）")]
        public static void ActorAutoStand(System.Int32 actorId, System.Int32 autoStand)
        {
            Pal3.Instance.Execute(new ActorAutoStandCommand(actorId, autoStand));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorChangeColliderSetting", "设置某个角色是否可以重叠（关闭碰撞）,参数：角色ID，是否可重叠(1可0不可)")]
        public static void ActorChangeColliderSetting(System.Int32 actorId, System.Int32 disableCollider)
        {
            Pal3.Instance.Execute(new ActorChangeColliderSettingCommand(actorId, disableCollider));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorChangeScale", "指定角色的缩放系数，参数：角色ID，缩放系数")]
        public static void ActorChangeScale(System.Int32 actorId, System.Single scale)
        {
            Pal3.Instance.Execute(new ActorChangeScaleCommand(actorId, scale));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorChangeTexture", "给角色更换纹理贴图参数：角色ID，贴图名")]
        public static void ActorChangeTexture(System.Int32 actorId, System.String textureName)
        {
            Pal3.Instance.Execute(new ActorChangeTextureCommand(actorId, textureName));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorChangeTransparency", "更改角色透明度，参数：角色ID，透明度(0-1f)")]
        public static void ActorChangeTransparency(System.Int32 actorId, System.Single alpha)
        {
            Pal3.Instance.Execute(new ActorChangeTransparencyCommand(actorId, alpha));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorEnablePlayerControl", "设置玩家控制哪个主角，参数：主角ID")]
        public static void ActorEnablePlayerControl(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new ActorEnablePlayerControlCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorFadeIn", "角色淡入")]
        public static void ActorFadeIn(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new ActorFadeInCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorFadeOut", "角色淡出")]
        public static void ActorFadeOut(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new ActorFadeOutCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorLoadAction", "使角色预加载一个动作，参数：角色ID，动作编号")]
        public static void ActorLoadAction(System.Int32 actorId, System.String actionName)
        {
            Pal3.Instance.Execute(new ActorLoadActionCommand(actorId, actionName));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorLookAtActor", "设定一个角色面向另一个角色（的位置），参数：被设置的角色的ID，面向的角色的ID")]
        public static void ActorLookAtActor(System.Int32 actorId, System.Int32 lookAtActorId)
        {
            Pal3.Instance.Execute(new ActorLookAtActorCommand(actorId, lookAtActorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorMoveBackwards", "角色向后平移，参数：角色ID，距离（原GameBox引擎下的距离单位）")]
        public static void ActorMoveBackwards(System.Int32 actorId, System.Single gameBoxDistance)
        {
            Pal3.Instance.Execute(new ActorMoveBackwardsCommand(actorId, gameBoxDistance));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorMoveOutOfScreen", "使角色向指定位置走,直到走出屏幕（不一定走到指定的点），参数：角色ID，TileMap中X坐标，TileMap中Y坐标，运动模式（0走，1跑）")]
        public static void ActorMoveOutOfScreen(System.Int32 actorId, System.Int32 tileXPosition, System.Int32 tileYPosition, System.Int32 mode)
        {
            Pal3.Instance.Execute(new ActorMoveOutOfScreenCommand(actorId, tileXPosition, tileYPosition, mode));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorMoveTo", "查找一个到TileMap上（X，Y）的路径，并使角色按此路径移动，移动中使用指定动作参数：角色ID，TileMap中X坐标，TileMap中Y坐标，动作类型（0走，1跑，2后退）")]
        public static void ActorMoveTo(System.Int32 actorId, System.Int32 tileXPosition, System.Int32 tileYPosition, System.Int32 mode)
        {
            Pal3.Instance.Execute(new ActorMoveToCommand(actorId, tileXPosition, tileYPosition, mode));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorPathTo", "查找一个到TileMap上（X，Y）的路径，并使角色按此路径移动，参数：角色ID，TileMap中X坐标，TileMap中Y坐标，运动模式（0走，1跑，2后退）")]
        public static void ActorPathTo(System.Int32 actorId, System.Int32 tileXPosition, System.Int32 tileYPosition, System.Int32 mode)
        {
            Pal3.Instance.Execute(new ActorPathToCommand(actorId, tileXPosition, tileYPosition, mode));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorPerformAction", "使角色执行一个动作，参数：角色ID，动作编号，播放次数（-1表示一直循环播放,-2表示播放一次后保持）")]
        public static void ActorPerformAction(System.Int32 actorId, System.String actionName, System.Int32 loopCount)
        {
            Pal3.Instance.Execute(new ActorPerformActionCommand(actorId, actionName, loopCount));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorPerformClimbAction", "使当前玩家操纵角色攀爬场景物品，参数：场景物品ID，向上或向下（1上0下）")]
        public static void ActorPerformClimbAction(System.Int32 objectId, System.Int32 climbUp)
        {
            Pal3.Instance.Execute(new ActorPerformClimbActionCommand(objectId, climbUp));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorRotateFacing", "转动角色面向的方向，参数：角色ID，转过多少角度（-360~360）")]
        public static void ActorRotateFacing(System.Int32 actorId, System.Int32 degrees)
        {
            Pal3.Instance.Execute(new ActorRotateFacingCommand(actorId, degrees));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorRotateFacingDirection", "转动角色的方向，参数：ID，方向（方向值为0-7）")]
        public static void ActorRotateFacingDirection(System.Int32 actorId, System.Int32 direction)
        {
            Pal3.Instance.Execute(new ActorRotateFacingDirectionCommand(actorId, direction));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetAttributeToFull", "设置主角的某项属性为满值，例如精加满，参数：角色ID，属性值类型")]
        public static void ActorSetAttributeToFull(System.Int32 actorId, System.Int32 attributeType)
        {
            Pal3.Instance.Execute(new ActorSetAttributeToFullCommand(actorId, attributeType));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetAttributeValue", "设置角色某项属性值的数值参数：角色ID，属性值类型，数值")]
        public static void ActorSetAttributeValue(System.Int32 actorId, System.Int32 attributeType, System.Int32 value)
        {
            Pal3.Instance.Execute(new ActorSetAttributeValueCommand(actorId, attributeType, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetFacingDirection", "瞬间使角色面向的方向改变，参数：角色ID，方向（方向值为0-7）")]
        public static void ActorSetFacingDirection(System.Int32 actorId, System.Int32 direction)
        {
            Pal3.Instance.Execute(new ActorSetFacingDirectionCommand(actorId, direction));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetNavLayer", "设置角色所在的地层，参数：ID，层数（0或1）")]
        public static void ActorSetNavLayer(System.Int32 actorId, System.Int32 layerIndex)
        {
            Pal3.Instance.Execute(new ActorSetNavLayerCommand(actorId, layerIndex));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetScript", "设置角色的对话脚本，参数：角色ID，脚本ID")]
        public static void ActorSetScript(System.Int32 actorId, System.Int32 scriptId)
        {
            Pal3.Instance.Execute(new ActorSetScriptCommand(actorId, scriptId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetTilePosition", "瞬间移动角色到TileMap中该点，参数：角色ID，TileMap中X坐标，TileMap中Y坐标")]
        public static void ActorSetTilePosition(System.Int32 actorId, System.Int32 tileXPosition, System.Int32 tileYPosition)
        {
            Pal3.Instance.Execute(new ActorSetTilePositionCommand(actorId, tileXPosition, tileYPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorSetYPosition", "给角色设置Y坐标参数：角色ID，Y坐标（原GameBox引擎下的Y坐标单位）")]
        public static void ActorSetYPosition(System.Int32 actorId, System.Single gameBoxYPosition)
        {
            Pal3.Instance.Execute(new ActorSetYPositionCommand(actorId, gameBoxYPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorShowEmoji2", "在角色头顶出现表情符号，参数：角色ID，表情编号ID")]
        public static void ActorShowEmoji2(System.Int32 actorId, System.Int32 emojiId)
        {
            Pal3.Instance.Execute(new ActorShowEmoji2Command(actorId, emojiId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorShowEmoji", "在角色头顶出现表情符号，参数：角色ID，表情编号ID")]
        public static void ActorShowEmoji(System.Int32 actorId, System.Int32 emojiId)
        {
            Pal3.Instance.Execute(new ActorShowEmojiCommand(actorId, emojiId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorStopActionAndStand", "使角色结束当前行为，并站立在当前位置，参数：角色ID")]
        public static void ActorStopActionAndStand(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new ActorStopActionAndStandCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorStopAction", "ActorPerformActionCommand的循环次数为-1或-2时需要用此命令结束，参数：角色ID")]
        public static void ActorStopAction(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new ActorStopActionCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ActorWalkToUsingAction", "查找一个到TileMap上（X，Y）的路径，并使角色按此路径走动，参数：角色ID，TileMap中X坐标，TileMap中Y坐标，动作名")]
        public static void ActorWalkToUsingAction(System.Int32 actorId, System.Int32 tileXPosition, System.Int32 tileYPosition, System.String action)
        {
            Pal3.Instance.Execute(new ActorWalkToUsingActionCommand(actorId, tileXPosition, tileYPosition, action));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFadeIn", "屏幕淡入")]
        public static void CameraFadeIn()
        {
            Pal3.Instance.Execute(new CameraFadeInCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFadeInWhite", "屏幕淡入(白色）")]
        public static void CameraFadeInWhite()
        {
            Pal3.Instance.Execute(new CameraFadeInWhiteCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFadeOut", "屏幕淡出")]
        public static void CameraFadeOut()
        {
            Pal3.Instance.Execute(new CameraFadeOutCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFadeOutWhite", "屏幕淡出（白色）")]
        public static void CameraFadeOutWhite()
        {
            Pal3.Instance.Execute(new CameraFadeOutWhiteCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFocusOnActor", "设置摄像机锁定角色，参数：角色ID")]
        public static void CameraFocusOnActor(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new CameraFocusOnActorCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFocusOnPosition", "设置摄像机视角锁定一个定点，参数：原GameBox引擎下的一个三维坐标（X，Y，Z）")]
        public static void CameraFocusOnPosition(System.Single gameBoxXPosition, System.Single gameBoxYPosition, System.Single gameBoxZPosition)
        {
            Pal3.Instance.Execute(new CameraFocusOnPositionCommand(gameBoxXPosition, gameBoxYPosition, gameBoxZPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFocusOnSceneObject", "设置摄像机锁定场景物品，参数：物品ID")]
        public static void CameraFocusOnSceneObject(System.Int32 sceneObjectId)
        {
            Pal3.Instance.Execute(new CameraFocusOnSceneObjectCommand(sceneObjectId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraFollowPlayer", "镜头是否锁定并跟随在主角身上，参数：1锁定并跟随，0解锁")]
        public static void CameraFollowPlayer(System.Int32 follow)
        {
            Pal3.Instance.Execute(new CameraFollowPlayerCommand(follow));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraMove", "镜头当前位置移动（保持当前角度），参数：原GameBox引擎下的一个三维坐标（X，Y，Z），动作时间，插值类型，同步（1暂停当前脚本运行，0异步进行动画且继续执行脚本）")]
        public static void CameraMove(System.Single gameBoxXPosition, System.Single gameBoxYPosition, System.Single gameBoxZPosition, System.Single duration, System.Int32 curveType, System.Int32 synchronous)
        {
            Pal3.Instance.Execute(new CameraMoveCommand(gameBoxXPosition, gameBoxYPosition, gameBoxZPosition, duration, curveType, synchronous));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraMoveToDefaultLookAtPoint", "相机移动至默认焦距点（主角）")]
        public static void CameraMoveToDefaultLookAtPoint(System.Int32 duration)
        {
            Pal3.Instance.Execute(new CameraMoveToDefaultLookAtPointCommand(duration));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraMoveToLookAtPoint", "移动相机并看向固定点")]
        public static void CameraMoveToLookAtPoint(System.Single gameBoxXPosition, System.Single gameBoxYPosition, System.Single gameBoxZPosition, System.Int32 synchronous)
        {
            Pal3.Instance.Execute(new CameraMoveToLookAtPointCommand(gameBoxXPosition, gameBoxYPosition, gameBoxZPosition, synchronous));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraOrbit", "镜头环绕LookAt位置旋转（LookAt点固定），参数：目标Yaw，Pitch，运动时间，插值类型（0：Linear，1：Sine）")]
        public static void CameraOrbit(System.Single yaw, System.Single pitch, System.Single duration, System.Int32 curveType)
        {
            Pal3.Instance.Execute(new CameraOrbitCommand(yaw, pitch, duration, curveType));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraOrbitHorizontal", "镜头朝向固定点左右Orbit参数：目标Yaw，Pitch，目标镜头距离（原GameBox引擎下的距离单位），运动时间，插值类型（0：Linear，1：Sine），同步（1暂停当前脚本运行，0异步进行动画且继续执行脚本）")]
        public static void CameraOrbitHorizontal(System.Single yaw, System.Single pitch, System.Single gameBoxDistance, System.Single duration, System.Int32 curveType, System.Int32 synchronous)
        {
            Pal3.Instance.Execute(new CameraOrbitHorizontalCommand(yaw, pitch, gameBoxDistance, duration, curveType, synchronous));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraOrbitVertical", "镜头朝向固定点上下Orbit参数：目标Yaw，Pitch，目标镜头距离（原GameBox引擎下的距离单位），运动时间，插值类型（0：Linear，1：Sine），同步（1暂停当前脚本运行，0异步进行动画且继续执行脚本）")]
        public static void CameraOrbitVertical(System.Single yaw, System.Single pitch, System.Single gameBoxDistance, System.Single duration, System.Int32 curveType, System.Int32 synchronous)
        {
            Pal3.Instance.Execute(new CameraOrbitVerticalCommand(yaw, pitch, gameBoxDistance, duration, curveType, synchronous));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraPopState", "取出镜头状态")]
        public static void CameraPopState()
        {
            Pal3.Instance.Execute(new CameraPopStateCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraPush", "镜头推动作，参数：最后from与lookAt之间的距离（原GameBox引擎下的距离单位），动作时间，插值类型（0：Linear，1：Sine），同步（1暂停当前脚本运行，0异步进行动画且继续执行脚本）")]
        public static void CameraPush(System.Single gameBoxDistance, System.Single duration, System.Int32 curveType, System.Int32 synchronous)
        {
            Pal3.Instance.Execute(new CameraPushCommand(gameBoxDistance, duration, curveType, synchronous));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraPushState", "保存镜头状态")]
        public static void CameraPushState()
        {
            Pal3.Instance.Execute(new CameraPushStateCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraRotate", "镜头摇动（from点固定），参数：目标Yaw，Pitch，运动时间，插值类型（0：Linear，1：Sine），                         同步（1暂停当前脚本运行，0异步进行动画且继续执行脚本）")]
        public static void CameraRotate(System.Single yaw, System.Single pitch, System.Single duration, System.Int32 curveType, System.Int32 synchronous)
        {
            Pal3.Instance.Execute(new CameraRotateCommand(yaw, pitch, duration, curveType, synchronous));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraSetDefaultTransform", "调用默认镜头参数，参数：镜头参数ID")]
        public static void CameraSetDefaultTransform(System.Int32 option)
        {
            Pal3.Instance.Execute(new CameraSetDefaultTransformCommand(option));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraSetTransform", "设置镜头参数，参数：Yaw，Pitch，Distance（原GameBox引擎下的距离单位），原GameBox引擎下的一个三维坐标（X，Y，Z）")]
        public static void CameraSetTransform(System.Single yaw, System.Single pitch, System.Single gameBoxDistance, System.Single gameBoxXPosition, System.Single gameBoxYPosition, System.Single gameBoxZPosition)
        {
            Pal3.Instance.Execute(new CameraSetTransformCommand(yaw, pitch, gameBoxDistance, gameBoxXPosition, gameBoxYPosition, gameBoxZPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraSetYaw", "相机设置Yaw角度")]
        public static void CameraSetYaw(System.Single yaw)
        {
            Pal3.Instance.Execute(new CameraSetYawCommand(yaw));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CameraShakeEffect", "摇晃镜头（模拟地震）效果，参数：持续时间，振幅")]
        public static void CameraShakeEffect(System.Single duration, System.Single amplitude)
        {
            Pal3.Instance.Execute(new CameraShakeEffectCommand(duration, amplitude));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CombatEnterBossFight", "进入Boss战")]
        public static void CombatEnterBossFight(System.UInt32 monster1Id, System.UInt32 monster2Id, System.UInt32 monster3Id, System.UInt32 monster4Id, System.UInt32 monster5Id, System.UInt32 monster6Id)
        {
            Pal3.Instance.Execute(new CombatEnterBossFightCommand(monster1Id, monster2Id, monster3Id, monster4Id, monster5Id, monster6Id));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CombatEnterBossFightUsingMusic", "进入Boss战斗并使用指定音乐")]
        public static void CombatEnterBossFightUsingMusic(System.UInt32 monster1Id, System.UInt32 monster2Id, System.UInt32 monster3Id, System.UInt32 monster4Id, System.UInt32 monster5Id, System.UInt32 monster6Id, System.String combatMusicName)
        {
            Pal3.Instance.Execute(new CombatEnterBossFightUsingMusicCommand(monster1Id, monster2Id, monster3Id, monster4Id, monster5Id, monster6Id, combatMusicName));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CombatEnterBossFightUsingMusicWithSpecialActor", "南宫煌以变身状态下进入Boss战斗")]
        public static void CombatEnterBossFightUsingMusicWithSpecialActor(System.UInt32 monster1Id, System.UInt32 monster2Id, System.UInt32 monster3Id, System.UInt32 monster4Id, System.UInt32 monster5Id, System.UInt32 monster6Id, System.String combatMusicName, System.Int32 combatCommandId)
        {
            Pal3.Instance.Execute(new CombatEnterBossFightUsingMusicWithSpecialActorCommand(monster1Id, monster2Id, monster3Id, monster4Id, monster5Id, monster6Id, combatMusicName, combatCommandId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CombatEnterNormalFight", "进入普通战斗")]
        public static void CombatEnterNormalFight(System.UInt32 numberOfMonster, System.UInt32 monster1Id, System.UInt32 monster2Id, System.UInt32 monster3Id)
        {
            Pal3.Instance.Execute(new CombatEnterNormalFightCommand(numberOfMonster, monster1Id, monster2Id, monster3Id));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CombatSetMaxRound", "设置战斗的最大回合数")]
        public static void CombatSetMaxRound(System.Int32 maxRound)
        {
            Pal3.Instance.Execute(new CombatSetMaxRoundCommand(maxRound));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CombatSetNoGameOverWhenLose", "设置战斗失败不显示结束游戏")]
        public static void CombatSetNoGameOverWhenLose()
        {
            Pal3.Instance.Execute(new CombatSetNoGameOverWhenLoseCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("CombatSetUnbeatable", "设置战斗为必败")]
        public static void CombatSetUnbeatable()
        {
            Pal3.Instance.Execute(new CombatSetUnbeatableCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("DialogueRenderActorAvatar", "渲染人物头像立绘，参数：角色ID，头像图片编号，问或答（0头像在左，1头像在右）")]
        public static void DialogueRenderActorAvatar(System.Int32 actorId, System.String avatarTextureName, System.Int32 rightAligned)
        {
            Pal3.Instance.Execute(new DialogueRenderActorAvatarCommand(actorId, avatarTextureName, rightAligned));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("DialogueRenderText", "显示对话，等待用户确定后脚本继续")]
        public static void DialogueRenderText(System.String dialogueText)
        {
            Pal3.Instance.Execute(new DialogueRenderTextCommand(dialogueText));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("DialogueRenderTextWithTimeLimit", "显示对话，等待用户确定后或者时间结束时脚本继续")]
        public static void DialogueRenderTextWithTimeLimit(System.String dialogueText)
        {
            Pal3.Instance.Execute(new DialogueRenderTextWithTimeLimitCommand(dialogueText));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("EffectAttachToActor", "在角色位置播放特效，参数：角色ID")]
        public static void EffectAttachToActor(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new EffectAttachToActorCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("EffectPlay", "播放VFX特效，参数：VFX特效GroupID")]
        public static void EffectPlay(System.Int32 effectGroupId)
        {
            Pal3.Instance.Execute(new EffectPlayCommand(effectGroupId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("EffectPreLoad", "预加载VFX特效Group，参数：VFX特效GroupID")]
        public static void EffectPreLoad(System.Int32 effectGroupId)
        {
            Pal3.Instance.Execute(new EffectPreLoadCommand(effectGroupId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("EffectSetPosition", "设置VFX特效位置，参数：原GameBox引擎下的一个三维坐标（X，Y，Z）")]
        public static void EffectSetPosition(System.Single gameBoxXPosition, System.Single gameBoxYPosition, System.Single gameBoxZPosition)
        {
            Pal3.Instance.Execute(new EffectSetPositionCommand(gameBoxXPosition, gameBoxYPosition, gameBoxZPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("EffectSetScreenEffect", "设置全局镜头（屏幕）特效，参数：特效模式（-1清除所有特效，0水下效果，1黑白色阶）")]
        public static void EffectSetScreenEffect(System.Int32 mode)
        {
            Pal3.Instance.Execute(new EffectSetScreenEffectCommand(mode));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("EffectShowSnow", "开启下雪特效，参数：0关闭，1开启")]
        public static void EffectShowSnow(System.Int32 active)
        {
            Pal3.Instance.Execute(new EffectShowSnowCommand(active));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("EffectShowWaterMagic", "在玩家角色周身渲染水特效，参数：0关闭，1开启")]
        public static void EffectShowWaterMagic(System.Int32 active)
        {
            Pal3.Instance.Execute(new EffectShowWaterMagicCommand(active));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("FavorAdd", "增减好感增，参数：角色ID，增减值")]
        public static void FavorAdd(System.Int32 actorId, System.Int32 changeAmount)
        {
            Pal3.Instance.Execute(new FavorAddCommand(actorId, changeAmount));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("FeatureEnableJusticeBook", "打开或关闭降妖谱功能，参数：0关闭，1打开")]
        public static void FeatureEnableJusticeBook(System.Int32 enable)
        {
            Pal3.Instance.Execute(new FeatureEnableJusticeBookCommand(enable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("FengYaSong", "控制雷元戈头上鸟（风雅颂）的显示与隐藏参数：模型类型（0=风，1=雅，2=颂，3=关闭），动作类型（0=静止，1=飞行）")]
        public static void FengYaSong(System.Int32 modelType, System.Int32 actionType)
        {
            Pal3.Instance.Execute(new FengYaSongCommand(modelType, actionType));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("FlyingActorFlyTo", "让桃子飞到某空间点参数：原GameBox引擎下的一个三维坐标（X，Y，Z）")]
        public static void FlyingActorFlyTo(System.Single gameBoxXPosition, System.Single gameBoxYPosition, System.Single gameBoxZPosition)
        {
            Pal3.Instance.Execute(new FlyingActorFlyToCommand(gameBoxXPosition, gameBoxYPosition, gameBoxZPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("GameComplete", "PAL3A游戏结束的最后一个指令，标示游戏通关")]
        public static void GameComplete()
        {
            Pal3.Instance.Execute(new GameCompleteCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("GameSwitchRenderingState", "选择当前渲染状态")]
        public static void GameSwitchRenderingState(System.Int32 state)
        {
            Pal3.Instance.Execute(new GameSwitchRenderingStateCommand(state));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("GameSwitchToMainMenu", "退出游戏到主菜单")]
        public static void GameSwitchToMainMenu()
        {
            Pal3.Instance.Execute(new GameSwitchToMainMenuCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("HuaYingSwitchBehaviourMode", "设置花盈的行为模式,参数：0：隐藏，1：跟随雪见，2：单飞")]
        public static void HuaYingSwitchBehaviourMode(System.Int32 mode)
        {
            Pal3.Instance.Execute(new HuaYingSwitchBehaviourModeCommand(mode));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("InventoryAddItem", "增加物品，参数：物品ID，个数")]
        public static void InventoryAddItem(System.Int32 itemId, System.Int32 count)
        {
            Pal3.Instance.Execute(new InventoryAddItemCommand(itemId, count));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("InventoryAddMoney", "增减金钱，参数：增减量")]
        public static void InventoryAddMoney(System.Int32 changeAmount)
        {
            Pal3.Instance.Execute(new InventoryAddMoneyCommand(changeAmount));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("InventoryRemoveItem", "拿走一个物品，参数：物品ID")]
        public static void InventoryRemoveItem(System.Int32 itemId)
        {
            Pal3.Instance.Execute(new InventoryRemoveItemCommand(itemId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("MiniGameStartGhostHunting", "PAL3A捉鬼（龙葵）游戏")]
        public static void MiniGameStartGhostHunting()
        {
            Pal3.Instance.Execute(new MiniGameStartGhostHuntingCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("NanGongHuangDisableTransformEffect", "关闭南宫煌身体异常时（快要变身）的特效")]
        public static void NanGongHuangDisableTransformEffect()
        {
            Pal3.Instance.Execute(new NanGongHuangDisableTransformEffectCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("NanGongHuangEnableTransformEffect", "开启南宫煌身体异常时（快要变身）的特效")]
        public static void NanGongHuangEnableTransformEffect()
        {
            Pal3.Instance.Execute(new NanGongHuangEnableTransformEffectCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("NavigationBeeFlyTo", "控制引路蜂飞向指定位置参数：Nav层，TileMap中X坐标，TileMap中Y坐标")]
        public static void NavigationBeeFlyTo(System.Int32 navLayerIndex, System.Int32 tileXPosition, System.Int32 tileYPosition)
        {
            Pal3.Instance.Execute(new NavigationBeeFlyToCommand(navLayerIndex, tileXPosition, tileYPosition));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayerEnableInput", "是否允许玩家控制当前主角，参数：0不可以，1可以")]
        public static void PlayerEnableInput(System.Int32 enable)
        {
            Pal3.Instance.Execute(new PlayerEnableInputCommand(enable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayerInteractWithObject", "与指定场景物品交互，参数：场景物品ID")]
        public static void PlayerInteractWithObject(System.Int32 sceneObjectId)
        {
            Pal3.Instance.Execute(new PlayerInteractWithObjectCommand(sceneObjectId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayerLearnCompose", "学会合成术，参数：合成物品的ID")]
        public static void PlayerLearnCompose(System.Int32 objectId)
        {
            Pal3.Instance.Execute(new PlayerLearnComposeCommand(objectId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayerSetActorLevel", "设置目标角色等级（所有当前角色等级的平均值+增加值），参数：角色ID，等级增加值")]
        public static void PlayerSetActorLevel(System.Int32 actorId, System.Int32 unknown1, System.Int32 unknown2, System.Int32 levelIncrease)
        {
            Pal3.Instance.Execute(new PlayerSetActorLevelCommand(actorId, unknown1, unknown2, levelIncrease));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayScriptMusic", "播放剧情音乐")]
        public static void PlayScriptMusic(System.String musicName, System.Int32 loop)
        {
            Pal3.Instance.Execute(new PlayScriptMusicCommand(musicName, loop));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlaySfx", "播放音效，参数：音效名，循环次数（0表示开始无限循环，-1表示结束循环）")]
        public static void PlaySfx(System.String sfxName, System.Int32 loopCount)
        {
            Pal3.Instance.Execute(new PlaySfxCommand(sfxName, loopCount));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("PlayVideo", "播放动画")]
        public static void PlayVideo(System.String name)
        {
            Pal3.Instance.Execute(new PlayVideoCommand(name));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneActivateObject", "设置某个物件出现或隐藏，参数：物件ID，是否出现（0隐藏，1出现）")]
        public static void SceneActivateObject(System.Int32 objectId, System.Int32 isActive)
        {
            Pal3.Instance.Execute(new SceneActivateObjectCommand(objectId, isActive));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneCloseDoor", "播放门关闭的动画")]
        public static void SceneCloseDoor(System.Int32 objectId)
        {
            Pal3.Instance.Execute(new SceneCloseDoorCommand(objectId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneEnableFog", "设置并开启场景内的雾气显示，参数：起始距离（原GameBox引擎下的距离单位），结束距离（原GameBox引擎下的距离单位），强度值，蓝色(0f-255f)，绿色(0f-255f)，红色(0f-255f)，透明度(0f-1f)")]
        public static void SceneEnableFog(System.Single startDistance, System.Single endDistance, System.Single intensity, System.Single blue, System.Single green, System.Single red, System.Single alpha)
        {
            Pal3.Instance.Execute(new SceneEnableFogCommand(startDistance, endDistance, intensity, blue, green, red, alpha));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneLoad", "切换场景，参数：场景城市/关卡（文件）名称，场景名称")]
        public static void SceneLoad(System.String sceneCityName, System.String sceneName)
        {
            Pal3.Instance.Execute(new SceneLoadCommand(sceneCityName, sceneName));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneMoveObject", "移动场景物体到某处，参数：物件ID，原GameBox引擎下的一个三维坐标插值（X，Y，Z），动画时间")]
        public static void SceneMoveObject(System.Int32 objectId, System.Single gameBoxXOffset, System.Single gameBoxYOffset, System.Single gameBoxZOffset, System.Single duration)
        {
            Pal3.Instance.Execute(new SceneMoveObjectCommand(objectId, gameBoxXOffset, gameBoxYOffset, gameBoxZOffset, duration));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneObjectDoNotLoadFromSaveState", "设置某个物件出场时候的不从存档里拿状态，参数：物件ID")]
        public static void SceneObjectDoNotLoadFromSaveState(System.Int32 objectId)
        {
            Pal3.Instance.Execute(new SceneObjectDoNotLoadFromSaveStateCommand(objectId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneOpenDoor", "播放门打开的动画")]
        public static void SceneOpenDoor(System.Int32 objectId)
        {
            Pal3.Instance.Execute(new SceneOpenDoorCommand(objectId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("SceneRotateWorld", "旋转整个场景，参数：原GameBox坐标系下的X轴旋转角度, Y轴旋转角度, Z轴旋转角度，动画时间，旋转正反向")]
        public static void SceneRotateWorld(System.Int32 xDegrees, System.Int32 yDegrees, System.Int32 zDegrees, System.Int32 duration, System.Int32 inverse)
        {
            Pal3.Instance.Execute(new SceneRotateWorldCommand(xDegrees, yDegrees, zDegrees, duration, inverse));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIfActorInTeam", "检测角色是否在队伍里并与临时变量计算结果，参数：角色ID")]
        public static void ScriptEvaluateVarIfActorInTeam(System.Int32 actorId)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIfActorInTeamCommand(actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIfPlayerHaveItem", "检查玩家是否拥有某个物品并与临时变量计算结果，参数：该物品的数据库ID")]
        public static void ScriptEvaluateVarIfPlayerHaveItem(System.Int32 itemId)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIfPlayerHaveItemCommand(itemId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsEqualTo", "判断变量是否等于给定值并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsEqualTo(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsEqualToCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsGreaterThan", "判断变量是否大于给定值并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsGreaterThan(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsGreaterThanCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsGreaterThanOrEqualTo", "判断变量是否大于等于给定值并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsGreaterThanOrEqualTo(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsGreaterThanOrEqualToCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsGreaterThanOrEqualToAnotherVar", "判断变量A的值是否大于等于变量B的值并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsGreaterThanOrEqualToAnotherVar(System.UInt16 variableA, System.UInt16 variableB)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsGreaterThanOrEqualToAnotherVarCommand(variableA, variableB));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsInRange", "判断变量值是否在给定区间范围内并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsInRange(System.UInt16 variable, System.Int32 min, System.Int32 max)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsInRangeCommand(variable, min, max));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsLessThan", "判断变量是否小于给定值并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsLessThan(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsLessThanCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsLessThanOrEqualTo", "判断变量是否小于等于给定值并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsLessThanOrEqualTo(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsLessThanOrEqualToCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptEvaluateVarIsNotEqualTo", "判断变量是否不等于给定值并与临时变量计算结果")]
        public static void ScriptEvaluateVarIsNotEqualTo(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptEvaluateVarIsNotEqualToCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptExecute", "调用另一段脚本，参数：脚本ID")]
        public static void ScriptExecute(System.Int32 scriptId)
        {
            Pal3.Instance.Execute(new ScriptExecuteCommand(scriptId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptRunnerChangeExecutionMode", "设置脚本运行模式，参数：1为异步执行，2为同步（顺序）执行")]
        public static void ScriptRunnerChangeExecutionMode(System.Int32 mode)
        {
            Pal3.Instance.Execute(new ScriptRunnerChangeExecutionModeCommand(mode));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptRunnerGoto", "使脚本跳转到指定位置，参数：脚本数据offset偏移值位置")]
        public static void ScriptRunnerGoto(System.Int32 offset)
        {
            Pal3.Instance.Execute(new ScriptRunnerGotoCommand(offset));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptRunnerGotoIfNot", "如果当前计算值为true的话就继续执行下一行指令，否则使脚本跳转至Offset处运行，参数：条件判定失败时所执行的脚本数据offset偏移值位置")]
        public static void ScriptRunnerGotoIfNot(System.Int32 offset)
        {
            Pal3.Instance.Execute(new ScriptRunnerGotoIfNotCommand(offset));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptRunnerSetOperator", "指定逻辑指令与标志变量的操作，参数：0：赋值/替换，1：与，2：或")]
        public static void ScriptRunnerSetOperator(System.Int32 operatorType)
        {
            Pal3.Instance.Execute(new ScriptRunnerSetOperatorCommand(operatorType));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptRunnerWaitUntilTime", "脚本在一定时间后才执行下一条指令（不影响游戏系统和其它脚本的执行），参数：time（秒）")]
        public static void ScriptRunnerWaitUntilTime(System.Single time)
        {
            Pal3.Instance.Execute(new ScriptRunnerWaitUntilTimeCommand(time));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarAddValue", "给变量增加值，Var += Value，参数：变量名（ID），值")]
        public static void ScriptVarAddValue(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptVarAddValueCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarDistractAnotherVar", "变量A减去B，如果减去后A小于零则A取反，并把结算结果重新赋值给变量A参数：变量名A，变量名B")]
        public static void ScriptVarDistractAnotherVar(System.UInt16 variableA, System.UInt16 variableB)
        {
            Pal3.Instance.Execute(new ScriptVarDistractAnotherVarCommand(variableA, variableB));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetActorFavor", "取出好感值并赋值给变量，参数：用户变量，角色ID")]
        public static void ScriptVarSetActorFavor(System.UInt16 variable, System.Int32 actorId)
        {
            Pal3.Instance.Execute(new ScriptVarSetActorFavorCommand(variable, actorId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetCombatResult", "取得战斗结果（0输1赢）并赋值给变量，参数：变量名")]
        public static void ScriptVarSetCombatResult(System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetCombatResultCommand(variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetDialogueSelectionResult", "取得选择结果并赋值给变量，参数：变量名")]
        public static void ScriptVarSetDialogueSelectionResult(System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetDialogueSelectionResultCommand(variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetLeastFavorableActorId", "取得主角对谁的好感最低并赋值给变量，参数：变量名")]
        public static void ScriptVarSetLeastFavorableActorId(System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetLeastFavorableActorIdCommand(variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetLimitTimeDialogueSelectionResult", "取得限时选择结果并赋值给变量，参数：变量名")]
        public static void ScriptVarSetLimitTimeDialogueSelectionResult(System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetLimitTimeDialogueSelectionResultCommand(variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetMazeSwitchStatus", "脚本检查迷宫开关状态并赋值给变量，参数：场景名，场景开关ID，变量名")]
        public static void ScriptVarSetMazeSwitchStatus(System.String sceneName, System.Int32 objectId, System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetMazeSwitchStatusCommand(sceneName, objectId, variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetMoney", "取出当前金钱数并赋值给变量，参数：变量名")]
        public static void ScriptVarSetMoney(System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetMoneyCommand(variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetMostFavorableActorId", "取得主角对谁的好感最高并赋值给变量，参数：变量名")]
        public static void ScriptVarSetMostFavorableActorId(System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetMostFavorableActorIdCommand(variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetObjectUsageStatus", "检测场景中物品（宝箱）是否被完全使用过并赋值给变量，参数：场景名，物件ID，变量名")]
        public static void ScriptVarSetObjectUsageStatus(System.String sceneName, System.Int32 objectId, System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetObjectUsageStatusCommand(sceneName, objectId, variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetRandomValue", "给变量随机赋值一个正整数，参数：输出变量，随机值上限（最大值但不包括）；输出0到最大值之间的一个整数")]
        public static void ScriptVarSetRandomValue(System.UInt16 variable, System.Int32 maxExclusiveValue)
        {
            Pal3.Instance.Execute(new ScriptVarSetRandomValueCommand(variable, maxExclusiveValue));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetValue", "给变量赋值，Var <== Value，参数：变量名（ID），值")]
        public static void ScriptVarSetValue(System.UInt16 variable, System.Int32 value)
        {
            Pal3.Instance.Execute(new ScriptVarSetValueCommand(variable, value));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("ScriptVarSetWheelOfTheFiveElementsUsageCount", "取出五灵轮当前使用次数并赋值给变量，参数：变量名")]
        public static void ScriptVarSetWheelOfTheFiveElementsUsageCount(System.UInt16 variable)
        {
            Pal3.Instance.Execute(new ScriptVarSetWheelOfTheFiveElementsUsageCountCommand(variable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("StopScriptMusic", "停止剧情音乐")]
        public static void StopScriptMusic()
        {
            Pal3.Instance.Execute(new StopScriptMusicCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TaskComplete", "完成主线或支线任务，参数：任务ID")]
        public static void TaskComplete(System.String taskId)
        {
            Pal3.Instance.Execute(new TaskCompleteCommand(taskId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TaskOpen", "开启主线或支线任务，参数：任务ID")]
        public static void TaskOpen(System.String taskId)
        {
            Pal3.Instance.Execute(new TaskOpenCommand(taskId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TeamAddOrRemoveActor", "设置某个主角是否在队伍中出现，参数：主角ID，是否出现（1出现0不出现）")]
        public static void TeamAddOrRemoveActor(System.Int32 actorId, System.Int32 isIn)
        {
            Pal3.Instance.Execute(new TeamAddOrRemoveActorCommand(actorId, isIn));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TeamClose", "玩家队伍合并")]
        public static void TeamClose()
        {
            Pal3.Instance.Execute(new TeamCloseCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TeamCloseOnSceneChange", "出情节关时队伍合并")]
        public static void TeamCloseOnSceneChange()
        {
            Pal3.Instance.Execute(new TeamCloseOnSceneChangeCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TeamOpen", "玩家队伍散开")]
        public static void TeamOpen()
        {
            Pal3.Instance.Execute(new TeamOpenCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TeamOpenOnSceneChange", "进入情节关时队伍散开")]
        public static void TeamOpenOnSceneChange()
        {
            Pal3.Instance.Execute(new TeamOpenOnSceneChangeCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("TeamSetAttributeToFull", "瞬间回满全队精气神")]
        public static void TeamSetAttributeToFull()
        {
            Pal3.Instance.Execute(new TeamSetAttributeToFullCommand());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("UIDisplayCaption", "显示全屏字幕（例如显示诗句等），参数：字幕序号（对应美术图片，每个字幕一个图片），列数，是否还有下一行")]
        public static void UIDisplayCaption(System.String textureName, System.Int32 numberOfLines, System.Int32 hasNextRow)
        {
            Pal3.Instance.Execute(new UIDisplayCaptionCommand(textureName, numberOfLines, hasNextRow));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("UIDisplayNextCaption", "显示全屏字幕（例如显示诗句等），参数：字幕序号（对应美术图片，每个字幕一个图片），列数")]
        public static void UIDisplayNextCaption(System.String textureName, System.Int32 numberOfLines)
        {
            Pal3.Instance.Execute(new UIDisplayNextCaptionCommand(textureName, numberOfLines));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("UIDisplayNote", "显示提示框信息")]
        public static void UIDisplayNote(System.String note)
        {
            Pal3.Instance.Execute(new UIDisplayNoteCommand(note));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("UIShowDealerMenu", "调用买卖系统，参数：商店数据文件名")]
        public static void UIShowDealerMenu(System.String dealerScriptName)
        {
            Pal3.Instance.Execute(new UIShowDealerMenuCommand(dealerScriptName));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("UIShowHotelMenu", "显示客栈入住菜单参数：客栈脚本文件名，可以入住脚本ID，不可以入住脚本ID，住宿脚本ID")]
        public static void UIShowHotelMenu(System.String hotelScriptName, System.Int32 canRestScriptId, System.Int32 cannotRestScriptId, System.Int32 afterRestScriptId)
        {
            Pal3.Instance.Execute(new UIShowHotelMenuCommand(hotelScriptName, canRestScriptId, cannotRestScriptId, afterRestScriptId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("UIShowSmeltingMenu", "打开冶炼菜单")]
        public static void UIShowSmeltingMenu(System.Int32 smeltingScriptId)
        {
            Pal3.Instance.Execute(new UIShowSmeltingMenuCommand(smeltingScriptId));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown166", "???")]
        public static void Unknown166(System.Int32 unknown1, System.Int32 unknown2)
        {
            Pal3.Instance.Execute(new UnknownCommand166(unknown1, unknown2));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown167", "在场景固定位置处播放特效（蜀山雷电特效）")]
        public static void Unknown167(System.String unknown1, System.Int32 unknown2, System.Single unknown3, System.Single unknown4, System.Single unknown5, System.Single unknown6, System.Single unknown7, System.Single unknown8)
        {
            Pal3.Instance.Execute(new UnknownCommand167(unknown1, unknown2, unknown3, unknown4, unknown5, unknown6, unknown7, unknown8));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown176", "南宫煌开启摄灵法阵")]
        public static void Unknown176(System.Int32 unknown1, System.Int32 unknown2, System.Int32 unknown3)
        {
            Pal3.Instance.Execute(new UnknownCommand176(unknown1, unknown2, unknown3));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown181", "???")]
        public static void Unknown181(System.Single unknown1, System.Single unknown2, System.Single unknown3, System.Single unknown4)
        {
            Pal3.Instance.Execute(new UnknownCommand181(unknown1, unknown2, unknown3, unknown4));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown185", "PAL3A打开算命小游戏UI")]
        public static void Unknown185(System.Int32 unknown1, System.Int32 unknown2, System.Int32 unknown3, System.Int32 unknown4, System.Int32 unknown5, System.Int32 unknown6, System.Int32 unknown7, System.Int32 unknown8)
        {
            Pal3.Instance.Execute(new UnknownCommand185(unknown1, unknown2, unknown3, unknown4, unknown5, unknown6, unknown7, unknown8));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown193", "???")]
        public static void Unknown193(System.Int32 unknown1, System.Int32 unknown2)
        {
            Pal3.Instance.Execute(new UnknownCommand193(unknown1, unknown2));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown196", "???")]
        public static void Unknown196()
        {
            Pal3.Instance.Execute(new UnknownCommand196());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown197", "设置风雅颂宿主角色ID？")]
        public static void Unknown197(System.Int32 actorId, System.Int32 enable)
        {
            Pal3.Instance.Execute(new UnknownCommand197(actorId, enable));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown198", "???")]
        public static void Unknown198(System.Int32 unknown1, System.Int32 unknown2)
        {
            Pal3.Instance.Execute(new UnknownCommand198(unknown1, unknown2));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("Unknown216", "???")]
        public static void Unknown216()
        {
            Pal3.Instance.Execute(new UnknownCommand216());
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("WangPengXuEnableCombatTransform", "设置开启/关闭王蓬絮战斗中变身（朱仙变），参数：0关闭，1开启")]
        public static void WangPengXuEnableCombatTransform(System.Int32 enabled)
        {
            Pal3.Instance.Execute(new WangPengXuEnableCombatTransformCommand(enabled));
        }

        // <auto-generated/>
        [ConsoleMethodAttribute("WorldMapEnableRegion", "大地图打开或关闭某个区域，参数：区域ID，0关闭，1显示但不可飞行，2显示且可以飞行")]
        public static void WorldMapEnableRegion(System.Int32 region, System.Int32 enablementFlag)
        {
            Pal3.Instance.Execute(new WorldMapEnableRegionCommand(region, enablementFlag));
        }
    }
}

#endif