name: Pal3.Unity CI

on: [push, pull_request]

jobs:
  build_pal3:
    name: Build PAL3 for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
        exclude:
          - targetPlatform: Android # Re-enable this once Unity fixed JDK path issue with headless build.
        buildName: PAL3
        versioning: Semantic
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: PAL3-Mono-Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
  build_pal3a:
    name: Build PAL3A for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
        exclude:
          - targetPlatform: Android # Re-enable this once Unity fixed JDK path issue with headless build.
        buildName: PAL3A
        versioning: Semantic
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Switch define symbol from PAL3 to PAL3A
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "PAL3"
          replace: "PAL3A"
          include: "**ProjectSettings.asset"
      - name: Replace PAL3 game icon with PAL3A one
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "6b32649dccc45df4ebe8e3f8eccee249"
          replace: "d03d417e5660d5849939c8fe43732dbd"
          include: "**ProjectSettings.asset"
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          allowDirtyBuild: true
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: PAL3A-Mono-Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}